force-app/main/default/objects/Contact/fields/MasterContact__c.field-meta.xml
<CustomField>
    <fullName>MasterContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master Contact record to which this Duplicate Contact should be merged.</description>
    <label>Master Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Duplicate Prospects</relationshipLabel>
    <relationshipName>MasterContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MergeApproved__c.field-meta.xml
<CustomField>
    <fullName>MergeApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Merge of Prospect to Client record has been approved.</description>
    <label>Merge Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TDA_Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>TDA_Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TDA_ODS_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>TDA_ODS_Client_ID__c</fullName>
    <externalId>true</externalId>
    <label>ODS Client ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client Record Type for mastered Clients</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Prospects who have not yet purchased Products and established a business relationship</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/classes/ContactMergeBatch_Test.cls
@IsTest
public class ContactMergeBatch_Test {

    @testsetup
    public static void setup() {
       // Create some contacts with duplicates for our scenarios
       List<Account> testAccounts = Test.loadData(Account.sobjectType,'TestAccounts');
       List<Contact> testContacts = Test.loadData(Contact.sobjectType,'TestContacts');
        
    }

    private static testmethod void testMatchMode() {
        Test.startTest();

        final Integer batchScope = 50; // Limit to 50 records per execution to avoid limits
        Database.executeBatch(new ContactMergeBatch('SELECT Id From Contact Where TDA_Contact_Type__c=\'Prospect\''
                              ,'Match'),batchScope);

        Test.stopTest();

        /**
         * When the Match operation completes, we should have 1 or more successful
         * matches saved 
         **/ 

         System.Assert(![SELECT Id 
                        From Contact 
                        Where TDA_Contact_Type__c='Prospect'
                          and MasterContact__c != null].isEmpty(),'Expected matches!');

    }

    private static testmethod void testMergeMode() {
        Test.startTest();

        // Prerun the match, save Matches 
        final List<Contact> prospects = [SELECT Id, Name, TDA_Contact_Type__c, Email, Phone, Title, TDA_ODS_Client_ID__c 
        FROM Contact 
        WHERE TDA_Contact_Type__c = 'Prospect' 
        LIMIT 1000];

        ContactMergeUtility merger = new ContactMergeUtility(prospects,'Client');
        merger.match();
        merger.saveMatches(merger.matchResults);


        // now execute the batch

        Database.executeBatch(new ContactMergeBatch('SELECT Id, TDA_Contact_Type__c, MergeApproved__c, MasterContact__c From Contact Where TDA_Contact_Type__c=\'Prospect\''
                              ,'Merge'));

        Test.stopTest();

        /**
         * When the Merge operation completes, we should no Prospects left needing
         * to be merged 
         **/ 
         System.Assert([SELECT Id 
                        From Contact 
                        Where TDA_Contact_Type__c='Prospect'
                          and MergeApproved__c=true].isEmpty(),'Expected no unmerged Prospects!');

    }
}